version: '3.5'
services:
  minio:
    build: minio
    image: user_minio:1.0.0
    command: server --console-address ":9001" /user_data
    environment:
      MINIO_ROOT_USER: 9Z939G61IPEV0WFHWIW1
      MINIO_ROOT_PASSWORD: krPc7XIcvXPCGnZpX1BtMnmWr4OaTzXqsH+50Jd6
    ports:
      - "83:9000"
      - "84:9001"
    networks:
      - user_ntwrk

  user-service:
    build: user-service
    image: user-service:1.0.0
    networks:
      - user_ntwrk
    depends_on:
      - db

  db:
    build: mysql
    image: mysql8.0:1.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myname
      MYSQL_PASSWORD: myname
    ports:
      - "3307:3306"
    networks:
      - user_ntwrk

  proxy:
    build: proxy
    ports:
      - "80:80"
    networks:
      - user_ntwrk
    depends_on:
      - user-service

networks:
    user_ntwrk:
      name: user_ntwrk