version: '3.5'
services:
  minio:
    build: minio
    image: user_minio:1.0.0
    command: server --console-address ":9001" /user_data
    environment:
      MINIO_ROOT_USER: 9Z939G61IPEV0WFHWIW1
      MINIO_ROOT_PASSWORD: krPc7XIcvXPCGnZpX1BtMnmWr4OaTzXqsH+50Jd6
    ports:
      - "83:9000"
      - "84:9001"
    networks:
      - user_ntwrk

  mysql:
    build: mysql
    image: mysql8.0:1.0.0
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: user-service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  dao:
    image: dao
    depends_on:
      - mysql  

  core:
    image: core
    depends_on:
      - mysql
      - dao
  web:
    image: web
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - dao
      - core

  proxy:
    build: proxy
    ports:
      - "80:80"
    networks:
      - user_ntwrk
    depends_on:
      - web

  networks:
    user_ntwrk:
      name: user_ntwrk