version: '3.5'
services:
  mysql:
    build: mysql
    image: mysql8.0:1.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DATABASE: user-service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  core:
    image: core
    environment:
      MYSQL_HOST: user-service
      MYSQL_PORT: 3306
      MYSQL_DATABASE: user-service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql
      - dao
  web:
    image: web
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - dao
      - core
  dao:
    image: dao
    environment:
      MYSQL_HOST: user-service
      MYSQL_PORT: 3306
      MYSQL_DATABASE: user-service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql